name: greposync
description: Keep Git repositories in sync
author: ccremer
inputs:
  version:
    description: greposync version to use
    required: true
    default: latest
  args:
    description: arguments to pass to greposync
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        "$GITHUB_ACTION_PATH/greposync.sh"
